version: '3'

services:
  server:
    image: brunoprocopio/nest-rest-api
    container_name: SERVER
    depends_on:
      - db
    links:
      - db
    ports:
      - '80:3000'

  db:
    image: 'mongo'
    container_name: DB
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db
